---

- hosts: all
  become: true
  tasks:

  - name: update reposytory
    apt:
      update_cache: yes

  - name: install apache2.deb
    apt:
      name: apache2
      state: absent

  - name: install lib
    apt:
      name: libapache2-mod-php
      state: absent
